// Generated by gencpp from file dist_project/targets_data.msg
// DO NOT EDIT!


#ifndef DIST_PROJECT_MESSAGE_TARGETS_DATA_H
#define DIST_PROJECT_MESSAGE_TARGETS_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace dist_project
{
template <class ContainerAllocator>
struct targets_data_
{
  typedef targets_data_<ContainerAllocator> Type;

  targets_data_()
    : robot_id(0)
    , points()  {
    }
  targets_data_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _robot_id_type;
  _robot_id_type robot_id;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::dist_project::targets_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dist_project::targets_data_<ContainerAllocator> const> ConstPtr;

}; // struct targets_data_

typedef ::dist_project::targets_data_<std::allocator<void> > targets_data;

typedef boost::shared_ptr< ::dist_project::targets_data > targets_dataPtr;
typedef boost::shared_ptr< ::dist_project::targets_data const> targets_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dist_project::targets_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dist_project::targets_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dist_project::targets_data_<ContainerAllocator1> & lhs, const ::dist_project::targets_data_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dist_project::targets_data_<ContainerAllocator1> & lhs, const ::dist_project::targets_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dist_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dist_project::targets_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dist_project::targets_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::targets_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::targets_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::targets_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::targets_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dist_project::targets_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65ee33d4860b2ecbe331036c18715b97";
  }

  static const char* value(const ::dist_project::targets_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65ee33d4860b2ecbULL;
  static const uint64_t static_value2 = 0xe331036c18715b97ULL;
};

template<class ContainerAllocator>
struct DataType< ::dist_project::targets_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dist_project/targets_data";
  }

  static const char* value(const ::dist_project::targets_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dist_project::targets_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 robot_id\n"
"geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dist_project::targets_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dist_project::targets_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targets_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dist_project::targets_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dist_project::targets_data_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIST_PROJECT_MESSAGE_TARGETS_DATA_H
