// Generated by gencpp from file dist_project/target_assignment_data.msg
// DO NOT EDIT!


#ifndef DIST_PROJECT_MESSAGE_TARGET_ASSIGNMENT_DATA_H
#define DIST_PROJECT_MESSAGE_TARGET_ASSIGNMENT_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dist_project
{
template <class ContainerAllocator>
struct target_assignment_data_
{
  typedef target_assignment_data_<ContainerAllocator> Type;

  target_assignment_data_()
    : sender_robot_id(0)
    , assigned_robot_id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  target_assignment_data_(const ContainerAllocator& _alloc)
    : sender_robot_id(0)
    , assigned_robot_id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _sender_robot_id_type;
  _sender_robot_id_type sender_robot_id;

   typedef int64_t _assigned_robot_id_type;
  _assigned_robot_id_type assigned_robot_id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::dist_project::target_assignment_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dist_project::target_assignment_data_<ContainerAllocator> const> ConstPtr;

}; // struct target_assignment_data_

typedef ::dist_project::target_assignment_data_<std::allocator<void> > target_assignment_data;

typedef boost::shared_ptr< ::dist_project::target_assignment_data > target_assignment_dataPtr;
typedef boost::shared_ptr< ::dist_project::target_assignment_data const> target_assignment_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dist_project::target_assignment_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dist_project::target_assignment_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dist_project::target_assignment_data_<ContainerAllocator1> & lhs, const ::dist_project::target_assignment_data_<ContainerAllocator2> & rhs)
{
  return lhs.sender_robot_id == rhs.sender_robot_id &&
    lhs.assigned_robot_id == rhs.assigned_robot_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dist_project::target_assignment_data_<ContainerAllocator1> & lhs, const ::dist_project::target_assignment_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dist_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dist_project::target_assignment_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dist_project::target_assignment_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::target_assignment_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::target_assignment_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::target_assignment_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::target_assignment_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dist_project::target_assignment_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e421d61aefbe78f0d6c0c39a64cfb320";
  }

  static const char* value(const ::dist_project::target_assignment_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe421d61aefbe78f0ULL;
  static const uint64_t static_value2 = 0xd6c0c39a64cfb320ULL;
};

template<class ContainerAllocator>
struct DataType< ::dist_project::target_assignment_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dist_project/target_assignment_data";
  }

  static const char* value(const ::dist_project::target_assignment_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dist_project::target_assignment_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sender_robot_id\n"
"int64 assigned_robot_id\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dist_project::target_assignment_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dist_project::target_assignment_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender_robot_id);
      stream.next(m.assigned_robot_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_assignment_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dist_project::target_assignment_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dist_project::target_assignment_data_<ContainerAllocator>& v)
  {
    s << indent << "sender_robot_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sender_robot_id);
    s << indent << "assigned_robot_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.assigned_robot_id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIST_PROJECT_MESSAGE_TARGET_ASSIGNMENT_DATA_H
