// Generated by gencpp from file dist_project/uwb_data.msg
// DO NOT EDIT!


#ifndef DIST_PROJECT_MESSAGE_UWB_DATA_H
#define DIST_PROJECT_MESSAGE_UWB_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dist_project
{
template <class ContainerAllocator>
struct uwb_data_
{
  typedef uwb_data_<ContainerAllocator> Type;

  uwb_data_()
    : tag_id()
    , distance()  {
    }
  uwb_data_(const ContainerAllocator& _alloc)
    : tag_id(_alloc)
    , distance(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _tag_id_type;
  _tag_id_type tag_id;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::dist_project::uwb_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dist_project::uwb_data_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_data_

typedef ::dist_project::uwb_data_<std::allocator<void> > uwb_data;

typedef boost::shared_ptr< ::dist_project::uwb_data > uwb_dataPtr;
typedef boost::shared_ptr< ::dist_project::uwb_data const> uwb_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dist_project::uwb_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dist_project::uwb_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dist_project::uwb_data_<ContainerAllocator1> & lhs, const ::dist_project::uwb_data_<ContainerAllocator2> & rhs)
{
  return lhs.tag_id == rhs.tag_id &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dist_project::uwb_data_<ContainerAllocator1> & lhs, const ::dist_project::uwb_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dist_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dist_project::uwb_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dist_project::uwb_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::uwb_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dist_project::uwb_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::uwb_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dist_project::uwb_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dist_project::uwb_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17e78c3780628319859d2345ed3e02ce";
  }

  static const char* value(const ::dist_project::uwb_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17e78c3780628319ULL;
  static const uint64_t static_value2 = 0x859d2345ed3e02ceULL;
};

template<class ContainerAllocator>
struct DataType< ::dist_project::uwb_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dist_project/uwb_data";
  }

  static const char* value(const ::dist_project::uwb_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dist_project::uwb_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] tag_id\n"
"float64[] distance\n"
;
  }

  static const char* value(const ::dist_project::uwb_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dist_project::uwb_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_id);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dist_project::uwb_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dist_project::uwb_data_<ContainerAllocator>& v)
  {
    s << indent << "tag_id[]" << std::endl;
    for (size_t i = 0; i < v.tag_id.size(); ++i)
    {
      s << indent << "  tag_id[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.tag_id[i]);
    }
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIST_PROJECT_MESSAGE_UWB_DATA_H
